# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: hello-world

services:
  postgresql:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=hello-world
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 127.0.0.1:5432:5432
